#docker-compose.yml

services:
    server: 
        build: .
        container_name: server
        ports:
        - "5000:5000"

    client:
        build: . 
        container_name: client 
        depends_on:
            -server
        entrypoint: ["python", "/app/client.py"]
        