services:
  server:
    build: ./app/server
    ports:
      - "5000:5000"
    networks:
      - charging_network

  client:
    build: ./app/client
    depends_on:
      - server
    networks:
      - charging_network
    stdin_open: true       # <- mantém STDIN aberto
    tty: true              # <- aloca terminal pseudo-TTY


  charge-point:
    build: ./app/charge-point
    depends_on:
      - server
    networks:
      - charging_network

networks:
  charging_network:
    driver: bridge
