services:
  # BROKER BA
  broker_ba:
    image: eclipse-mosquitto
    container_name: broker_ba
    ports:
      - "1883:1884"
      - "1884:1884"

    volumes:
      - ./brokers/BA/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./brokers/BA/data:/mosquitto/data
      - ./brokers/BA/log:/mosquitto/log

  # BROKER SE
  broker_se:
    image: eclipse-mosquitto
    container_name: broker_se
    ports:
      - "1886:1883"
    volumes:
      - ./brokers/SE/config:/brokers/config
      - ./brokers/SE/data:/brokers/data
      - ./brokers/SE/log:/brokers/log

 # BROKER MA
  broker_ma:
    image: eclipse-mosquitto
    container_name: broker_ma
    ports:
      - "1885:1883"
    volumes:
      - ./brokers/MA/config:/brokers/config
      - ./brokers/MA/data:/brokers/data
      - ./brokers/MA/log:/brokers/log