services:
  broker_ba:
    image: eclipse-mosquitto
    container_name: broker_ba
    ports:
      - "1884:1883"
    volumes:
      - ./app/mosquitto/BA:/mosquitto/config


  server_ba:
    build:
      context: ./app/server/BA
      dockerfile: Dockerfile-server
    depends_on:
      - broker_ba
    ports:
      - "5001:5000"

