# Dockerfile para charge-point

FROM python:3.12-slim

WORKDIR /app

COPY charge-point.py .

# Instala as dependências
RUN pip install flask paho-mqtt==2.1.0 requests

CMD ["python3", "charge-point.py"]
