# Dockerfile para os charge-points
FROM python:3.10-slim

WORKDIR /app
COPY . .

# Variável de ambiente padrão (pode ser sobrescrita pelo docker-compose)
ENV NOME_CHARGE_POINT=charge-point-1

# CMD padrão inicia o script
CMD ["python3", "charge.py"]
